services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: samim123
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: samim123
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: samim123
      DB_NAME: odoo_db
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo

volumes:
  db_data:
  odoo_data:
