version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      DB_HOST: db
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: postgres
    volumes:
      - ./custom_addons:/mnt/extra-addons

volumes:
  db_data:
